### ISSUE TITLE
fails to build with libwebsockets 4.4.1

### ISSUE THREAD

**Issue by david-geiger** [deiv/driftnet#55]
Hi,

On Mageia Cauldron latest release 1.6.0 fails to build with libwebsockets 4.4.1, with the following build issue:

> httpd.c:196:9: error: initialization of 'unsigned char' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  196 |         NULL,

Attached full build log:

[build.x86_64.0.20250723041817.log](https://github.com/user-attachments/files/21379410/build.x86_64.0.20250723041817.log)

**Comment by PPN-SD** [comment]
Reproduced here (1.6.0/4.4.1), and it's not simple to fix it because values in httpd.c are not commented

```
httpd.c: In function ‘http_server_dispatch’:
httpd.c:194:9: warning: unsigned conversion from ‘int’ to ‘unsigned char:1’ changes value from ‘2’ to ‘0’ [-Woverflow]
  194 |         LWSMPRO_FILE,                   /* mount type is a directory in a filesystem */
      |         ^~~~~~~~~~~~
httpd.c:196:9: error: initialization of ‘unsigned char’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
  196 |         NULL,
      |         ^~~~
httpd.c:196:9: note: (near initialization for ‘mount.mountpoint_len’)
```

**Comment by PPN-SD** [comment]
Major changes in examples for 4.4 : 
https://github.com/warmcat/libwebsockets/blob/v4.4.1/minimal-examples-lowlevel/http-server/minimal-http-server/minimal-http-server.c#L22

It compiles with that but I can't test the webserver for now :
``` diff
--- a/src/http_display/httpd.c
+++ b/src/http_display/httpd.c
@@ -191,9 +191,18 @@ static void * http_server_dispatch(void *arg)
         0,
         0,
         0,
+#if LWS_LIBRARY_VERSION_MAJOR >= 4 && LWS_LIBRARY_VERSION_MINOR > 3
+       0,                              /* check cache always */
+#endif
         LWSMPRO_FILE,                  /* mount type is a directory in a filesystem */
         1,                                     /* strlen("/"), ie length of the mountpoint */
         NULL,
+#if LWS_LIBRARY_VERSION_MAJOR >= 4 && LWS_LIBRARY_VERSION_MINOR > 3
+       NULL,                           /* chroot_path */
+       NULL,                           /* working directory, default /tmp */
+       NULL,                           /* override the headers */
+       0,                              /* keepalive_timeout */
+#endif
 #if LWS_LIBRARY_VERSION_MAJOR <= 4 && LWS_LIBRARY_VERSION_MINOR < 3
         { NULL, NULL } // sentinel
 #endif
```
