### PR TITLE
switch to a simplified configuration for httpd

### LINKED ISSUE #55: fails to build with libwebsockets 4.4.1
Hi,

On Mageia Cauldron latest release 1.6.0 fails to build with libwebsockets 4.4.1, with the following build issue:

> httpd.c:196:9: error: initialization of 'unsigned char' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  196 |         NULL,

Attached full build log:

[build.x86_64.0.20250723041817.log](https://github.com/user-attachments/files/21379410/build.x86_64.0.20250723041817.log)

### PR DESCRIPTION
**Pull request by PPN-SD**
because params are default values

tested with libwebsockets-4.3/4.4 and driftnet-1.5.0 / 1.6.0

Closes: #55

### CODE REVIEW

**Comment by PPN-SD** [comment]
~~Not tested with driftnet 1.6.0 because I got an 404 error whatever with libwebsockets 4.3 or 4.4.~~

**Comment by deiv** [comment]
@PPN-SD At first sight, looks good to me. But it makes me doubt about the next points:

- **mime_types** was overriden to allow to recognize webp images (and some obscure jpeg too). So, this will not break that?
- If we are getting 404 in 1.6.0, then this change is in some way broken ?

**Comment by PPN-SD** [comment]
> @PPN-SD At first sight, looks good to me. But it makes me doubt about the next points:
> 
> - **mime_types** was overriden to allow to recognize webp images (and some obscure jpeg too). So, this will not break that?

hum, let me check. webp is not in libwebsocket list indeed.

> - If we are getting 404 in 1.6.0, then this change is in some way broken ?
> 

this is another issue. patch applied or not doesnt change anything. maybe html files needs to be installed in a specific dir ?

**Comment by deiv** [comment]
> > @PPN-SD At first sight, looks good to me. But it makes me doubt about the next points:
> > 
> > * **mime_types** was overriden to allow to recognize webp images (and some obscure jpeg too). So, this will not break that?
> 
> hum, let me check. webp is not in libwebsocket list indeed.

;)

> 
> > * If we are getting 404 in 1.6.0, then this change is in some way broken ?
> 
> this is another issue. patch applied or not doesnt change anything. maybe html files needs to be installed in a specific dir ?

Yep, static files, if not overriden, should live in /usr/share. For development purpouse try --enable-http-display-in-src-statics configure flag, that should do the job (src dir static files will be used instead of /usr/share ones).

**Comment by PPN-SD** [comment]
> --enable-http-display-in-src-statics

ok, it didn't work (err 404) with src-statics the last time I checked. Anyway, use files in /usr/share is fine. The question is why it doesnt work with 1.6 but does with 1.5.

**Comment by deiv** [comment]
> > --enable-http-display-in-src-statics
> 
> ok, it didn't work (err 404) with src-statics the last time I checked. Anyway, use files in /usr/share is fine. The question is why it doesnt work with 1.6 but does with 1.5.

Then, I'm not in the mood to merge the PR, until the situation is fixed.

Probably the 404 is related to the former changes.

**Comment by PPN-SD** [comment]
mime_types added and tested.
404 appears because the path for index.hml is wrong with 1.6.0 but not for 1.5.0, but it could be a side effect of the distribution.
