### ISSUE TITLE
make error on MAC

### ISSUE THREAD

**Issue by feng5** [deiv/driftnet#7]
```
$ make
Making all in src
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in media
make[3]: Nothing to be done for `all'.
Making all in display
make[3]: Nothing to be done for `all'.
  CC       layer2.o
layer2.c:12:10: fatal error: 'netinet/ether.h' file not found
#include <netinet/ether.h>
         ^
1 error generated.
make[3]: *** [layer2.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

**Comment by deiv** [comment]
Hi,

Could you change this header import in this file "layer2.c" from <netinet/ether.h> to <netinet/if_ether.h> and try again make.

Tell me if that worked pls.

**Comment by inu1255** [comment]
I'm MacOS 10.12
1. change [`src/layer2.c:12`](https://github.com/deiv/driftnet/blob/master/src/layer2.c#L12) `<netinet/ether.h>`  to `<netinet/if_ether.h>` 
or just run `sudo ln -s /usr/include/netinet/if_ether.h /usr/include/netinet/ether.h`
2. insert these lines to the top of `src/config.h`
``` c
#ifndef _FUCK_ETHER__
#define _FUCK_ETHER__
#define ETH_ALEN 6 
#define ETH_HLAN 14 
#define ETH_ZLEN 60 
#define ETH_DATA_LEN 1500 
#define ETH_FRAME_LEN 1514 
#define ETH_FCS_LEN 4  
#define ETH_P_IP 0x0800
#define ETH_P_IPV6 0x86DD
#define ETH_P_ARP 0x0806
#define ETH_P_PAE 0x888E

struct ethhdr
{
    unsigned char h_dest[ETH_ALEN];
    unsigned char h_source[ETH_ALEN];
    unsigned short h_proto;
}__attribute__((packed));
#endif
```
it works for me

**Comment by ohlinge** [comment]
@inu1255 Hi, 
 Can you tell me detailed steps to compile in Mac OS 10.12 ? 
please!

**Comment by deiv** [comment]
Fiexd by #19

**Comment by luckypoem** [comment]
@inu1255 
hi.
i ran "sudo ln -s /usr/include/netinet/if_ether.h /usr/include/netinet/ether.h"
it shows:
ln: /usr/include/netinet/ether.h: Operation not permitted

how to fix the "Operation not permitted" issue?

**Comment by IMO-Au** [comment]
@luckypoem Use the terminal in Recovery System and run "csrutil disable"
